jpsType: update
jpsVersion: '1.7.4'

name: Traefik.conf/Decidim
id: decidim-vanilla-traefik
description:
  short: Decidim Saas
categories:
  - apps/platforms
baseUrl: https://raw.githubusercontent.com/octree-gva/voca-jps/main
logo: assets/decidim_logo.png

settings:
  fields:
  - name: URL
    caption: URL
    type: string
  - name: ERROR_URL
    caption: ERROR_URL
    type: string
  - name: SERVICE_NAME
    caption: SERVICE_NAME
    type: string

onInstall:
  - cmd[cp]:
      - echo "[JELASTIC] ADD ${settings.SERVICE_NAME}" >> /var/log/run.log
      - export  URL="${settings.URL}" ERROR_URL="${settings.ERROR_URL}" SERVICE_NAME="${settings.SERVICE_NAME}"
      - echo "time=\"$(date +%FT%TZ)\" level=info msg=\"decidim $URL is in maintenance\"" >> /var/log/run.log
      - curl -s "https://raw.githubusercontent.com/octree-gva/voca-jps/main/templates/traefik-placeholder.yml" > /tmp/$SERVICE_NAME.yml
      - cd /config/hosts
      - (envsubst \$URL,\$SERVICE_NAME,\$ERROR_URL < /tmp/$SERVICE_NAME.yml) > ./$SERVICE_NAME.yml
      - echo "time=\"$(date +%FT%TZ)\" level=info msg=\"decidim $PWD/$SERVICE_NAME.yml up and running\"" >> /var/log/run.log
      - rm /tmp/$SERVICE_NAME.yml

